server:
  port: 5888
spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:mysql://192.168.100.194:3306/test?useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: hxzh
    password: 1Q2w3e4r5t!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect